Poste/Controllers/UserLoginController.cs
using Poste.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

/*namespace Poste.Controllers
{
    public class UserLoginController : Controller
    {
        // Metodo per visualizzare la pagina di login
        public ActionResult Index()
        {
            return View();
        }

        // Metodo per effettuare il login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Username, Password")] Users u)
        {
            string conn = ConfigurationManager.ConnectionStrings["ConnectionStringDB"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(conn);

            try
            {
                sqlConnection.Open();

                SqlCommand sqlCommand = new SqlCommand("select * from Users where Username=@Username and Password=@Password and Role='User'", sqlConnection);
                sqlCommand.Parameters.AddWithValue("Username", u.Username);
                sqlCommand.Parameters.AddWithValue("Password", u.Password);
                SqlDataReader reader = sqlCommand.ExecuteReader();

                if (reader.HasRows)
                {
                    // Imposta la sessione con il nome utente
                    Session["Username"] = u.Username;
                    FormsAuthentication.SetAuthCookie(u.Username, false);
                    return RedirectToAction("RegisterPackage", "Spedizioni");
                }
                else
                {
                    // Mostra un messaggio di errore se l'utente non è un amministratore
                    ViewBag.AuthError = "Non sei Utente";
                    return View();
                }
            }
            catch (Exception ex)
            {
                // Gestisci eventuali eccezioni
            }
            finally
            {
                // Chiudi la connessione al database
                sqlConnection.Close();
            }

            return View();
        }

        // Metodo per effettuare il logout dell'utente
        [HttpPost]
        public ActionResult Logout()
        {
            // Cancella la sessione e l'autenticazione dell'utente
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}*/
/*namespace Poste.Controllers
{
    public class UserLoginController : Controller
    {
        // Metodo per visualizzare la pagina di login
        [HttpGet]
        public ActionResult LoginUser()
        {
            return View();
        }

        // Metodo per effettuare il login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Username, Password")] Users u)
        {
            string conn = ConfigurationManager.ConnectionStrings["ConnectionStringDB"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(conn);

            try
            {
                sqlConnection.Open();

                SqlCommand sqlCommand = new SqlCommand("select * from Users where Username=@Username and Password=@Password and Role='User'", sqlConnection);
                sqlCommand.Parameters.AddWithValue("Username", u.Username);
                sqlCommand.Parameters.AddWithValue("Password", u.Password);
                SqlDataReader reader = sqlCommand.ExecuteReader();

                if (reader.HasRows)
                {
                    // Imposta la sessione con il nome utente
                    Session["Username"] = u.Username;
                    FormsAuthentication.SetAuthCookie(u.Username, false);
                    return RedirectToAction("RegisterPackage", "Spedizioni");
                }
                else
                {
                    // Mostra un messaggio di errore se l'utente non è un amministratore
                    ViewBag.AuthError = "Non sei Utente";
                    return View();
                }
            }
            catch (Exception ex)
            {
                // Gestisci eventuali eccezioni
            }
            finally
            {
                // Chiudi la connessione al database
                sqlConnection.Close();
            }

            return View();
        }
    }
}*/

Poste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poste Italiane</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<!-- //////////////////////////////////////////// NAVBAR /////////////////////////////////////////////-->
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm" style="background-color: #EEDC00;">
        <div class="container">
            @Html.ActionLink("Poste Italiane", "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-primary" })

            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "nav-link text-primary" })</li>
                    <!--<li>@Html.ActionLink("User", "Index", "UserLogin", new { area = "" }, new { @class = "nav-link text-primary" })</li>-->
                    <li>@Html.ActionLink("Tracking", "Index", "Tracking", new { area = "" }, new { @class = "nav-link text-primary" })</li>
                    <li>@Html.ActionLink("Contatti", "Contatti", "Home", new { area = "" }, new { @class = "nav-link text-primary" })</li>
                    <li>@Html.ActionLink("Informazioni", "Informazioni", "Home", new { area = "" }, new { @class = "nav-link text-primary" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- //////////////////////////////////////////// FOOTER /////////////////////////////////////////////-->
    <div class="container body-content ">
        @RenderBody()

        <footer class="bg-dark mb-1 w-100 justify-content-center rounded fixed-bottom">

            <div class="d-flex fex-row justify-content-around pt-3 rounded text-primary" style="background-color: #EEDC00">
                <p>&copy; @DateTime.Now.Year - Poste Italiane</p>
            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>